remote:
  fw: vsrx02
  network: 192.168.2.0/24
vpn_interface:
  name: st0
  unit: 0
  description: to_vsrx02
  address: 10.10.10.1/30
vpn:
  gateway:
    remote_address: 10.0.0.2
    local_interface: ge-0/0/1.0

