- name: Build and deploy Multipoint IPSec VPN configurations
  hosts: vsrx
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Build IPSec configurations
      template: src=ipsec_template.j2 dest={{ playbook_dir }}/Configs/{{ inventory_hostname }}.set

